#------------------------------------------------------------------------
# Compiled template generated by the Template Toolkit version 2.27
#------------------------------------------------------------------------

Template::Document->new({
    METADATA => {
        'name' => 'templates/footer.tt',
        'modtime' => '1543810242',
    },
    BLOCK => sub { return '' },
    DEFBLOCKS => {

    },
});
