use utf8;

#------------------------------------------------------------------------
# Compiled template generated by the Template Toolkit version 2.27
#------------------------------------------------------------------------

Template::Document->new({
    METADATA => {
        'name' => 'templates/header.tt',
        'modtime' => '1543858884',
    },
    BLOCK => sub {
    my $context = shift || die "template sub called without context\n";
    my $stash   = $context->stash;
    my $output  = '';
    my $_tt_error;
    
    eval { BLOCK: {
$output .=  "<header>\n  <a href=\"/about\"><h1 style=\"color: white\">[ 🐈 Pastey ]</h1></a>\n  <div><a \@click=\"onSave\">[ Save ]</a></div>\n  <div><a \@click=\"onCreate\">[ New ]</a></div>\n  <div><a \@click=\"onDupandEdit\">[ Duplicate & Edit ]</a></div>\n  <div><a \@click=\"getTextOnly\">[ Raw Text ]</a></div>\n</header>";
    } };
    if ($@) {
        $_tt_error = $context->catch($@, \$output);
        die $_tt_error unless $_tt_error->type eq 'return';
    }

    return $output;
},
    DEFBLOCKS => {

    },
});
